name: Build iOS App
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: |
        dotnet workload install maui maui-ios
        dotnet workload restore
    - run: dotnet restore
    - run: dotnet build -c Release -f net9.0-ios
    - uses: actions/upload-artifact@v4
      with:
        name: iOSApp
        path: '**/bin/Release/net9.0-ios/*.ipa'
