name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.4.app

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.303

    - name: Show installed SDK
      run: dotnet --info

    - name: Install MAUI workloads
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui --skip-manifest-update
        dotnet workload restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build iOS App
      run: dotnet build OccasionReminder.csproj -c Release -f net9.0-ios

    - name: Publish iOS IPA
      run: |
        dotnet publish OccasionReminder.csproj \
        -f net9.0-ios \
        -c Release \
        -p:ArchiveOnBuild=true \
        -p:RuntimeIdentifier=ios-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: '**/*.ipa'
